name: Build-ISO

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
      
    - name: Get ISO
      run: make download
      
    - name: Initialize
      run: make init
      
    - name: Setup env
      run: make setup

    - name: Build ISO
      run: make geniso

    - name: SharePoint uploader
      # You may pin to the exact commit or the version.
      # uses: su-dont/share-point-uploader@d5219f8801329ec36b7add0d3874a9df0564c577
      uses: su-dont/share-point-uploader@v2.1
      with:
        # SharePoint URL
        sp_url: https://glattgroup.sharepoint.com/sites/RA-PAD-Development
        # SharePoint Username
        sp_username: ${{ secrets.USER }}
        # SharePoint Password
        sp_password: ${{ secrets.PASSWORD }}
        # SharePoint destination folder
        sp_folder: Releases
        # SharePoint destination file name
        sp_file_name: GCH-ISO
        # File to be uploaded
        file: glatt-client*

    #- name: Upload a Build Artifact
    #  uses: actions/upload-artifact@v3.1.1
    #  with:
    #    # Artifact name
    #    name: BootISO # optional, default is artifact
    #    # A file, directory or wildcard pattern that describes what to upload
    #    path: glatt-client*
    #    #The desired behavior if no files are found using the provided path.
    #    retention-days: 1
